### ISSUE TITLE
Demo-Code mainpage works / th erest does not work

### ISSUE THREAD

**Issue by StefanL38** [alanesq/misc#1]
Hi alanesq,

I tried to use your updated VeryBasicWebserver.ino 

The mainpage is shown in my browsers (actual firefox / actual chrome) 
but as soon as I enter the url  http://192.168.178.96/test

I get an error-message
The serial debug-output looks like this

```
07:30:38.856 -> Webserver demo sketch
07:30:38.856 -> 
07:30:38.856 -> Connecting to FRITZ!Box 7490
07:30:38.856 ->    ...............
07:30:47.567 -> WiFi connected, IP address: 192.168.178.96
07:30:56.532 -> Root page requested
07:31:01.295 -> Test page requested
07:31:01.342 -> Test page requested
07:31:01.396 -> Test page requested
07:31:01.443 -> Test page requested
07:31:01.443 -> Test page requested
07:31:01.496 -> Test page requested
07:31:01.542 -> Test page requested
07:31:01.542 -> Test page requested
07:31:01.596 -> Test page requested
07:31:01.642 -> Test page requested
07:31:31.459 -> Root page requested
07:31:41.769 -> Test page requested
07:31:41.769 -> Test page requested
07:31:41.816 -> Test page requested
07:31:41.816 -> Test page requested
07:31:41.869 -> Test page requested
07:31:41.916 -> Test page requested
07:31:41.916 -> Test page requested
07:31:41.969 -> Test page requested
07:31:42.016 -> Test page requested
07:31:42.016 -> Test page requested

```

why the heck are the functions called again and again and again?
why do you call client.stop() after this very short delay of 3 milliseconds?

could it be that this demo-code worked for you only because all the website data was in your local cache?

best regards Stefan

**Comment by alanesq** [comment]
Hi,
I have just tried it myself (pasting the sketch from github) in both PlatformIO and Arduino IDE but it works ok for me.
If the root page is working ok for you but the others are not I really can't explain it as none of them are doing anything more complicated????
Do you have another device you can try accessing it from?   I am wondering if a firewall or something is blocking it?

Having said that they do use a different method from http://192.168.178.96/ so I am wondering if your esp32 board manager has not installed fully or maybe try an older version (as I have had a lot of issues with the latest ones - I ended up going back to v1.0.6)

**Comment by alanesq** [comment]
I did just have one thought that I kept the html header as small as possible and I wonder if your web browser is not happy with it as a result?
I have just modified the sketch to have a more "advanced" header and would be interested to know if this has resolved the issue for you?

**Comment by alanesq** [comment]
assuming this has resolved it
